.catalog:
  name: "Magento-Simple"
  version: "v0.1-magento"
  description: "Popular e-commerce platform"
  uuid: Magento-Simple-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: "FPM_HOST"
      label: "Php-fpm Hostname"
      required: false
      default: "php"
      type: "string"
    - variable: "FPM_PORT"
      label: "Php-fpm Port"
      required: false
      type: "string"
      default: "9000"
    - variable: "ENC_KEY"
      label: "Encryption Key For Magento"
      required: true
      type: "string"
      default: ""
    - variable: "ADMIN_NAME"
      label: "Admin URL"
      required: true
      type: "string"
      default: "admin"
    - variable: "MYSQL_DB"
      label: "Database Name"
      required: true
      type: "string"
      default: "magento"
    - variable: "MYSQL_HOST"
      description: "" 
      label: "MySQL Host"
      required: true
      type: "string"
      default: "mysql"
    - variable: "MYSQL_USER"
      description: "" 
      label: "MySQL User"
      required: true
      type: "string"
      default: ""
    - variable: "MYSQL_PASS"
      description: "" 
      label: "MySQL Password"
      required: true
      type: "string"
      default: ""
    - variable: "KEY"
      description: ""
      label: "Host Key"
      required: true
      type: "string"
      default: "io.alekseon.shared"
    - variable: "VALUE" 
      label: "Value For Host's Key"
      required: true
      type: "string"
      default: "true"
    - variable: "APP_LOCATION"
      description: "Needs to point src directory"
      label: "App Files Location On Host"
      required: true
      type: "string"
      default: ""
    - variable: "MYSQL_LOCATION" 
      label: "MySQL Location"
      required: true
      type: "string"
      default: "/var/lib/mysql"
magento:
